<a href="https://colab.research.google.com/github/iamBehzad/Five-Project-Advanced-Deep-Learning-Low-Level-Modeling/blob/main/Project05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras import layers
from keras import metrics

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('CarPrice_Assignment.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [ ]:
print ('\n=================================== ((((( missing values in DataFrame ))))) ===================================\n')
print(df.isnull().sum())

print ('\n=================================== ((((( There is no Missing Values ))))) ===================================\n')

X=df.drop(['price'], axis=1)
Y=df['price']


le = LabelEncoder()
X['CarName'] = le.fit_transform(X['CarName'])
X['fueltype'] = le.fit_transform(X['fueltype'])
X['aspiration'] = le.fit_transform(X['aspiration'])
X['doornumber'] = le.fit_transform(X['doornumber'])
X['carbody'] = le.fit_transform(X['carbody'])
X['drivewheel'] = le.fit_transform(X['drivewheel'])
X['enginelocation'] = le.fit_transform(X['enginelocation'])
X['enginetype'] = le.fit_transform(X['enginetype'])
X['cylindernumber'] = le.fit_transform(X['cylindernumber'])
X['fuelsystem'] = le.fit_transform(X['fuelsystem'])
X['CarName'] = le.fit_transform(X['CarName'])
X['fueltype'] = le.fit_transform(X['fueltype'])


print ('\n======================================= ((((( Type Of X DataFrame ))))) =======================================\n')
print(X.dtypes)

print ('\n======================================= ((((( Type Of Y DataFrame ))))) =======================================\n')
print(Y.dtypes)

print ('\n=================================== ((((( There is no object values ))))) ===================================\n')

=================================== ((((( missing values in DataFrame ))))) ===================================

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

=================================== ((((( There is no Missing Values ))))) ===================================


======================================= ((((( Type Of X DataFrame ))))) =======================================

car_ID                int64
symboling             int64
CarName               int64
fueltype              int64
aspiration            int64
doornumber            int64
carbody               int64
drivewheel            int64
enginelocation        int64
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype            int64
cylindernumber        int64
enginesize            int64
fuelsystem            int64
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
dtype: object

======================================= ((((( Type Of Y DataFrame ))))) =======================================

float64

=================================== ((((( There is no object values ))))) ===================================

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,Y)
x_train, x_val, y_train, y_val = train_test_split(x_train,y_train)

print("X_train.shape = ",x_train.shape)
print("y_train.shape = ",y_train.shape)
print("\nx_val.shape = ",x_val.shape)
print("y_val.shape = ",y_val.shape)
print("\nX_test.shape = ",x_test.shape)
print("y_test.shape = ",y_test.shape)

X_train.shape =  (114, 25)
y_train.shape =  (114,)

x_val.shape =  (39, 25)
y_val.shape =  (39,)

X_test.shape =  (52, 25)
y_test.shape =  (52,)

In [ ]:
SC=StandardScaler()
x_train = SC.fit_transform(x_train)
x_val = SC.fit_transform(x_val)
x_test = SC.fit_transform(x_test)

In [ ]:
model_My_loss = keras.models.Sequential([
  keras.layers.Dense(50, activation ="relu"),
  keras.layers.Dense(50, activation='relu'),
  keras.layers.Dense(50, activation='relu'),
  keras.layers.Dense(1)
])

In [ ]:
class My_loss(keras.losses.Loss):
  def __init__(self, e1, e2, l1, l2, l3, **kwargs):
    self.e1 = e1
    self.e2 = e2

    self.l1 = l1
    self.l2 = l2
    self.l3 = l3

    super().__init__(**kwargs)

  def call(self, y_true, y_pred):
    d = tf.abs(y_true - y_pred)
    #print("\n",tf.reduce_max(d))
    #print(tf.reduce_min(d))
    return tf.experimental.numpy.select(
        [d >= self.e1, tf.logical_and(d > self.e2, d < self.e1), d <= self.e2],
        [self.l3*d, self.l2*d, self.l1*d])

  def get_config(self):
    parent_config = super().get_config()
    return {**parent_config, "e1":self.e1, "e2":self.e2, "l1":self.l1, "l2":self.l2, "l3":self.l3}

In [ ]:
model = keras.models.Sequential([
  keras.layers.Dense(50, activation ="relu"),
  keras.layers.Dense(50, activation='relu'),
  keras.layers.Dense(50, activation='relu'),
  keras.layers.Dense(1)
])

loss_fn = My_loss(e1=10000, e2=5000, l1=1, l2=2, l3=4)
opt = tf.keras.optimizers.SGD(learning_rate=0.01)
train_mae = tf.keras.metrics.MeanAbsoluteError()
val_mae = tf.keras.metrics.MeanAbsoluteError()

In [ ]:
batch_size=32
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_data = train_data.shuffle(buffer_size=len(y_train)).batch(batch_size)

val_data = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_data = val_data.shuffle(buffer_size=len(y_val)).batch(batch_size)

In [ ]:
epochs = 100
for epoch in range(epochs):
  Loss_t=[]
  Loss_v=[]
  for batch_i, (xt, yt) in enumerate(train_data):
    with tf.GradientTape() as g:
      model_out_train = model(xt, training=True) 
      yt = tf.cast(yt, dtype=tf.double) 
      model_out_train = tf.cast(model_out_train, dtype=tf.double)
      loss_train = loss_fn(yt, model_out_train)
      Loss_t.append(loss_train)

    grads = g.gradient(loss_train, model.trainable_weights)
    opt.apply_gradients(zip(grads, model.trainable_weights))
    train_mae.update_state(yt, model_out_train)

  for batch_i, (xv, yv) in enumerate(val_data):
    model_out_val = model(xv, training=False) 
    yv = tf.cast(yv, dtype=tf.double) 
    model_out_val = tf.cast(model_out_val, dtype=tf.double)
    loss_train = loss_fn(yv, model_out_val)
    Loss_v.append(loss_train)
    val_mae.update_state(yv, model_out_val)

  
  if tf.logical_or( epoch < 5 , epoch % 10 == 0):
    print("\nepoch : ",epoch )
    print("Training loss:", float(tf.reduce_mean(Loss_t)))
    print("Validation loss:", float(tf.reduce_mean(Loss_v)))
    train_mae_val = train_mae.result()
    print("Train mae:", float(train_mae_val))
    val_mae_val = val_mae.result()
    print("Validation mae:", float(val_mae_val))

  train_mae.reset_states()
  val_mae.reset_states()

epoch :  0
Training loss: 15065.799850524902
Validation loss: 7609.752626068738
Train mae: 6180.0390625
Validation mae: 3789.758544921875

epoch :  1
Training loss: 14501.220319173177
Validation loss: 11959.784330912998
Train mae: 6068.751953125
Validation mae: 4753.126953125

epoch :  2
Training loss: 13999.004524291991
Validation loss: 9962.586113306941
Train mae: 5923.353515625
Validation mae: 4652.0244140625

epoch :  3
Training loss: 14631.364856357151
Validation loss: 8937.479929904548
Train mae: 6101.703125
Validation mae: 4501.39501953125

epoch :  4
Training loss: 15482.934281304253
Validation loss: 8029.552967071533
Train mae: 6337.07373046875
Validation mae: 4026.626220703125

epoch :  10
Training loss: 14962.812954433864
Validation loss: 8282.050048146928
Train mae: 6191.12548828125
Validation mae: 4214.8974609375

epoch :  20
Training loss: 13909.159847791883
Validation loss: 12116.290165219989
Train mae: 5924.8486328125
Validation mae: 4938.9091796875

epoch :  30
Training loss: 15250.977756985136
Validation loss: 11402.481563188592
Train mae: 6244.9775390625
Validation mae: 5077.57373046875

epoch :  40
Training loss: 14875.26527749973
Validation loss: 7303.874431746346
Train mae: 6193.86279296875
Validation mae: 3943.39111328125

epoch :  50
Training loss: 14583.68942945014
Validation loss: 9595.245252064296
Train mae: 6045.06103515625
Validation mae: 4324.029296875

epoch :  60
Training loss: 14590.504026733399
Validation loss: 6832.822640545514
Train mae: 6106.84765625
Validation mae: 3540.151611328125

epoch :  70
Training loss: 15578.706877875433
Validation loss: 6601.438259397234
Train mae: 6293.20751953125
Validation mae: 3610.8740234375

epoch :  80
Training loss: 15092.1440201416
Validation loss: 10442.823370184218
Train mae: 6183.66455078125
Validation mae: 4752.78662109375

epoch :  90
Training loss: 14674.418607984753
Validation loss: 12705.62866328687
Train mae: 6074.37548828125
Validation mae: 5222.748046875